var pageWidth = window.innerWidth;
var pageHeight = window.innerHeight;
var Sootnoshenie = pageWidth / 760;
window.addEventListener("resize", AutoScale);
AutoScale();
function AutoScale() {
    pageWidth = window.innerWidth;
    pageHeight = window.innerHeight;
    Sootnoshenie = pageWidth / 760;
    rez = document.getElementById("13d");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 303) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 14) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 63) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 240) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 63) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 18) + "px");
    rez = document.getElementById("H");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 300) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 24) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 63) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 163) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 64) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 31) + "px");
    rez = document.getElementById("NavText");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 14) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 258) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 30) + "px");
    rez = document.getElementById("LogoPic");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 136.48) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 55) + "px");
    rez = document.getElementById("b1InCatalog");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 130) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 30) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 215) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 320) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 13) + "px");
    rez = document.getElementById("text99");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 35) + "px");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 130) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 27) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 16) + "px");
    rez = document.getElementById("b1");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 130) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 30) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 63) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 320) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 13) + "px");
    rez = document.getElementById("text18");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 130) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 30) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 40) + "px");
    rez = document.getElementById("Header");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 70) + "px");
    rez = document.getElementById("Lupa");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 340) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 20) + "px");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 20) + "px");
    rez = document.getElementById("basket");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 375) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 20) + "px");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 20) + "px");
    rez = document.getElementById("section1");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 70) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 455) + "px");
    rez.style.setProperty("width", pageWidth + "px");
    rez = document.getElementById("flow");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 397) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 397) + "px");
    rez = document.getElementById("section2");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 525) + "px");
    rez.style.setProperty("width", pageWidth + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 405) + "px");
    rez = document.getElementById("bouquets");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 145) + "px");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 210) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 65) + "px");
    rez = document.getElementById("natural_flowers");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 145) + "px");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 210) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 275) + "px");
    rez = document.getElementById("own_bouquet");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 145) + "px");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 210) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 485) + "px");
    rez = document.getElementById("button3");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 30) + "px");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 130) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 315) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 108) + "px");
    rez = document.getElementById("button4");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 30) + "px");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 130) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 105) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 108) + "px");
    rez = document.getElementById("button5");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 30) + "px");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 130) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 525) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 108) + "px");
    rez = document.getElementById("1");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 28) + "px");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 139) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 65) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 191) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 24) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 31) + "px");
    rez = document.getElementById("palka");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 20) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 60) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 250) + "px");
    rez = document.getElementById("text2");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 309) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 56) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 80) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 237) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 14) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 18) + "px");
    rez = document.getElementById("abstract");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 317) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 270) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 443) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 211) + "px");
    rez = document.getElementById("women");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 320) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 180) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 401) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 225) + "px");
    rez = document.getElementById("vb");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 20) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 20) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 715) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 329) + "px");
    rez = document.getElementById("inst");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 20) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 20) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 715) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 258) + "px");
    rez = document.getElementById("fb");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 20) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 20) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 715) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 295) + "px");
    rez = document.getElementById("section3");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 930) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 156) + "px");
    rez.style.setProperty("width", pageWidth + "px");
    rez = document.getElementById("text4");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 224) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 28) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 63) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 7) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 16) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 20) + "px");
    rez = document.getElementById("text5");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 150) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 52) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 63) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 101) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 11) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 14) + "px");
    rez = document.getElementById("constructor");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 65) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 55) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 105) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 48) + "px");
    rez = document.getElementById("delivery");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 65) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 55) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 266) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 48) + "px");
    rez = document.getElementById("text6");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 150) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 52) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 224) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 101) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 11) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 14) + "px");
    rez = document.getElementById("indoor");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 62) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 63) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 429) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 46) + "px");
    rez = document.getElementById("text7");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 150) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 52) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 385) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 101) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 11) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 14) + "px");
    rez = document.getElementById("love");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 75) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 75) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 583) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 34) + "px");
    rez = document.getElementById("text8");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 150) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 52) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 546) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 101) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 11) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 14) + "px");
    rez = document.getElementById("section4");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 1086) + "px");
    rez.style.setProperty("width", pageWidth + "px");
    rez = document.getElementById("text15");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 139) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 28) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 64) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 47) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 24) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 31) + "px");
    rez = document.getElementById("cart1");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 331) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 65) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 104) + "px");
    rez = document.getElementById("cart2");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 331) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 280) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 104) + "px");
    rez = document.getElementById("11");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 200) + "px");
    rez = document.getElementById("21");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 200) + "px");
    rez = document.getElementById("31");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 200) + "px");
    rez = document.getElementById("41");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 200) + "px");
    rez = document.getElementById("51");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 200) + "px");
    rez = document.getElementById("61");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 200) + "px");
    rez = document.getElementById("cart3");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 331) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 495) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 104) + "px");
    rez = document.getElementById("cart4");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 331) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 65) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 455) + "px");
    rez = document.getElementById("cart5");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 331) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 280) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 455) + "px");
    rez = document.getElementById("cart6");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 331) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 495) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 455) + "px");
    rez = document.getElementById("text9");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 38) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 55) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 210) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 14) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 18) + "px");
    rez = document.getElementById("text11");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 38) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 55) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 210) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 14) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 18) + "px");
    rez = document.getElementById("text13");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 38) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 55) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 210) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 14) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 18) + "px");
    rez = document.getElementById("text156");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 38) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 55) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 210) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 14) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 18) + "px");
    rez = document.getElementById("text17");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 38) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 55) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 210) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 14) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 18) + "px");
    rez = document.getElementById("text19");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 38) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 55) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 210) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 14) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 18) + "px");
    rez = document.getElementById("text10");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 23) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 70) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 260) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 14) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 18) + "px");
    rez = document.getElementById("text12");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 23) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 70) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 260) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 14) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 18) + "px");
    rez = document.getElementById("text14");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 23) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 70) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 260) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 14) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 18) + "px");
    rez = document.getElementById("text16");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 23) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 70) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 260) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 14) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 18) + "px");
    rez = document.getElementById("text111");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 23) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 70) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 260) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 14) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 18) + "px");
    rez = document.getElementById("text20");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 23) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 70) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 260) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 14) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 18) + "px");
    rez = document.getElementById("b6");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 130) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 30) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 35) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 285) + "px");
    rez = document.getElementById("b7");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 130) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 30) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 35) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 285) + "px");
    rez = document.getElementById("b8");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 130) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 30) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 35) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 285) + "px");
    rez = document.getElementById("b9");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 130) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 30) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 35) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 285) + "px");
    rez = document.getElementById("b10");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 130) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 30) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 35) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 285) + "px");
    rez = document.getElementById("b11");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 130) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 30) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 35) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 285) + "px");
    rez = document.getElementById("arrows1");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 300) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 50) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 293) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 795) + "px");
    rez = document.getElementById("section5");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 1950) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 690) + "px");
    rez.style.setProperty("width", pageWidth + "px");
    rez = document.getElementById("text199");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 139) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 28) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 64) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 24) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 24) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 31) + "px");
    rez = document.getElementById("flowerss");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 600) + "px");
    rez.style.setProperty("bottom", Math.round(Sootnoshenie * 570) + "px");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 160) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 165) + "px");
    rez = document.getElementById("1-per-foto");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 64) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 75) + "px");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 100) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 100) + "px");
    rez.style.setProperty("border-radius", Math.round(Sootnoshenie * 100) + "px");
    rez = document.getElementById("text200");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 340) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 105) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 211) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 75) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 14) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 18) + "px");
    rez = document.getElementById("palka2");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 210) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 157) + "px");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 20) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 2) + "px");
    rez = document.getElementById("text21");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 149) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 16) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 211) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 162) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 13) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 16) + "px");
    rez = document.getElementById("2-per-foto");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 215) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 223) + "px");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 100) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 100) + "px");
    rez.style.setProperty("border-radius", Math.round(Sootnoshenie * 100) + "px");
    rez = document.getElementById("text22");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 340) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 105) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 360) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 223) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 14) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 18) + "px");
    rez = document.getElementById("flowers2");
    rez.style.setProperty("border-radius", Math.round(Sootnoshenie * 16) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 204) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 248) + "px");
    rez = document.getElementById("palka3");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 360) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 321) + "px");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 20) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 2) + "px");
    rez = document.getElementById("text23");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 149) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 16) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 360) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 328) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 13) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 16) + "px");
    rez = document.getElementById("arrows2");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 292) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 349) + "px");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 300) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 50) + "px");
    rez = document.getElementById("vid");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 172) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 27) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 64) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 433) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 20) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 26) + "px");
    rez = document.getElementById("ni");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 631) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 29) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 64) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 475) + "px");
    rez.style.setProperty("border-radius", Math.round(Sootnoshenie * 10) + "px");
    rez = document.getElementById("vi");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 631) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 94) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 64) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 516) + "px");
    rez.style.setProperty("border-radius", Math.round(Sootnoshenie * 10) + "px");
    rez = document.getElementById("send");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 130) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 30) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 61) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 625) + "px");
    rez.style.setProperty("border-radius", Math.round(Sootnoshenie * 50) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 14) + "px");
    rez = document.getElementById("dil");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 262) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 28) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 64) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 44) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 24) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 31) + "px");
    rez = document.getElementById("section6");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 2640) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 470) + "px");
    rez.style.setProperty("width", pageWidth + "px");
    rez = document.getElementById("eli1");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 65) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 65) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 127) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 100) + "px");
    rez.style.setProperty("border-radius", Math.round(Sootnoshenie * 50) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 40) + "px");
    rez = document.getElementById("a");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 52) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 80) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 173) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 13) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 16) + "px");
    rez = document.getElementById("eli2");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 65) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 65) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 347) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 100) + "px");
    rez.style.setProperty("border-radius", Math.round(Sootnoshenie * 50) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 40) + "px");
    rez = document.getElementById("b");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 70) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 280) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 173) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 13) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 16) + "px");
    rez = document.getElementById("eli3");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 65) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 65) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 567) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 100) + "px");
    rez.style.setProperty("border-radius", Math.round(Sootnoshenie * 50) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 40) + "px");
    rez = document.getElementById("c");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 86) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 510) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 165) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 13) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 16) + "px");
    rez = document.getElementById("eli4");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 65) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 65) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 127) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 265) + "px");
    rez.style.setProperty("border-radius", Math.round(Sootnoshenie * 50) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 40) + "px");
    rez = document.getElementById("e");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 86) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 310) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 330) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 13) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 16) + "px");
    rez = document.getElementById("d");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 66) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 80) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 340) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 13) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 16) + "px");
    rez = document.getElementById("eli5");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 65) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 65) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 347) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 265) + "px");
    rez.style.setProperty("border-radius", Math.round(Sootnoshenie * 50) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 40) + "px");
    rez = document.getElementById("f");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 86) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 520) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 330) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 13) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 16) + "px");
    rez = document.getElementById("eli6");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 65) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 65) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 567) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 265) + "px");
    rez.style.setProperty("border-radius", Math.round(Sootnoshenie * 50) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 40) + "px");
    rez = document.getElementById("logo2");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 136) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 55) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 312) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 6) + "px");
    rez = document.getElementById("table");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 65) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 65) + "px");
    rez = document.getElementById("end");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 14) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 18) + "px");
    rez = document.getElementById("end2");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 11) + "px");
    rez = document.getElementById("end3");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 11) + "px");
    rez = document.getElementById("end4");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 11) + "px");
    rez = document.getElementById("end5");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 11) + "px");
    rez = document.getElementById("ei");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 236) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 26) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 457) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 79) + "px");
    rez.style.setProperty("border-radius", Math.round(Sootnoshenie * 50) + "px");
    rez = document.getElementById("senb");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 92) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 27) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 606) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 79) + "px");
    rez.style.setProperty("border-radius", Math.round(Sootnoshenie * 50) + "px");
    rez = document.getElementById("contact");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 3110) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 185) + "px");
    rez.style.setProperty("width", pageWidth + "px");
    rez = document.getElementById("vb2");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 25) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 25) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 600) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 118) + "px");
    rez = document.getElementById("fb2");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 20) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 23) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 565) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 118) + "px");
    rez = document.getElementById("inst2");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 20) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 23) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 530) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 118) + "px");
    rez = document.getElementById("license");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 90) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 14) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 460) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 158) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 11) + "px");
    rez.style.setProperty("line-height", Math.round(Sootnoshenie * 14) + "px");
    rez = document.getElementById("flowers3");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 200) + "px");
    rez.style.setProperty("height", Math.round(Sootnoshenie * 350) + "px");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 560) + "px");
    rez.style.setProperty("top", Math.round(Sootnoshenie * 2950) + "px");
    rez = document.getElementById("flow3");
    rez.style.setProperty("left", Math.round(Sootnoshenie * 150) + "px");
    rez = document.getElementById("ErrorMessange");
    rez.style.setProperty("left", Math.round(pageWidth - Sootnoshenie * 300) + "px");
    rez.style.setProperty("width", Math.round(Sootnoshenie * 300) + "px");
    rez.style.setProperty("top", Math.round(pageHeight - Sootnoshenie * (pageWidth - Sootnoshenie * 700)) + "px");
    rez.style.setProperty("height", Math.round(pageWidth - Sootnoshenie * 700) + "px");
    rez.style.setProperty("font-size", Math.round(Sootnoshenie * 14) + "px");
}
animateDisplay = function (target, animationClass, displayType, timeout) {
    var doneTimedDisplay = false,
        displaying = false;
    target.addEventListener('transitionend', function () {
        if (!target.classList.contains('show')) {
            target.style.display = 'none';
        }
        doneTimedDisplay = true;
    });
    if (!target.style.display || target.style.display === 'none') {
        displaying = true;
        target.style.display = displayType;
    }
    setTimeout(function () {
        target.classList.toggle(animationClass);
        doneTimedDisplay = false;
    }, 10);
    if (!displaying) {
        setTimeout(function () {
            if (!doneTimedDisplay) {
                target.style.display = 'none';
            }
            doneTimedDisplay = true;
        }, timeout);
    }
    setTimeout(() => target.style.display = "none", 3000);
    displaying = false;
    doneTimedDisplay = false;
};
document.querySelector('.mybutt')
    .addEventListener('click', function () {
        animateDisplay(document.querySelector('.content'), 'show', 'block', 3000);
    });
document.querySelector('.mybutt2')
    .addEventListener('click', function () {
        animateDisplay(document.querySelector('.content'), 'show', 'block', 3000);
    });
document.querySelector('.mybutt3')
    .addEventListener('click', function () {
        animateDisplay(document.querySelector('.content'), 'show', 'block', 3000);
    });
document.querySelector('.mybutt4')
    .addEventListener('click', function () {
        animateDisplay(document.querySelector('.content'), 'show', 'block', 3000);
    });
document.querySelector('.mybutt5')
    .addEventListener('click', function () {
        animateDisplay(document.querySelector('.content'), 'show', 'block', 3000);
    });
document.querySelector('.mybutt6')
    .addEventListener('click', function () {
        animateDisplay(document.querySelector('.content'), 'show', 'block', 3000);
    });
document.querySelector('.mybutt7')
    .addEventListener('click', function () {
        animateDisplay(document.querySelector('.content'), 'show', 'block', 3000);
    });
document.querySelector('.mybutt8')
    .addEventListener('click', function () {
        animateDisplay(document.querySelector('.content'), 'show', 'block', 3000);
    });
document.querySelector('.mybutt9')
    .addEventListener('click', function () {
        animateDisplay(document.querySelector('.content'), 'show', 'block', 3000);
    });
    
    
const imageContainers = document.querySelectorAll('.image-container');

imageContainers.forEach((container) => {
  container.addEventListener('mouseenter', () => {
    container.classList.add('hovered');
  });
  container.addEventListener('mouseleave', () => {
    container.classList.remove('hovered');
  });
});